name: train-my-model

on: [issue_comment]

jobs:
  train:
    if: | 
      (github.event.issue.pull_request != null) &&
      contains(github.event.comment.body, '/nvidia-smi')    
    runs-on: [cml, gpu]

    steps:
      - uses: actions/checkout@v2
      - name: test
        env:
          repo_token: ${{ secrets.CML_GITHUB_TOKEN }}
        run: |
          CODEBLOCK="\`\`\`"
          echo $CODEBLOCK > report.md
          nvidia-smi >> report.md
          echo $CODEBLOCK >> report.md
          
          cml-send-comment report.md
