name: train-my-model

on: [issue_comment]

jobs:
  train:
    if: | 
      (github.event.issue.pull_request != null) &&
      contains(github.event.comment.body, '/nvidia-smi')    
    runs-on: [self-hosted, Linux, x64]

    steps:
      - uses: actions/checkout@v2

      - name: test
        run: |
          nvidia-smi > report.md
          cml-send-comment report.md --commit-sha d1b89c5af4183d7f75d610664c8af23f87909664
