name: train-my-model

on: [push]

jobs:
  train:
    runs-on: [self-hosted, macOS, x64]

    steps:
      - uses: actions/checkout@v2

      - name: test
        run: |
          echo 'Hi from Local GitHub Action runner!'
